console.log("=======Assignment 1=========");
console.log("_________Q1_________");
var firstName = "Sunil Naik";
console.log("Name==>",firstName,"data type==>",typeof firstName);
var mob = 8945763218;
console.log("mobile no.==>",mob, "data type==>",typeof mob);
var isPass = true;
console.log("Pass==>",isPass,"data type==>",typeof isPass);
console.log("_________Q2_________");
console.log("=======Difference Between Null and Undefined=========");
console.log("Null:-");
console.log("Null means the variable we used to store data has no value.");
console.log("There is nothing in the storage of that variable.");
console.log("Undefined:-");
console.log("Undefined means the variable will store the special keyword");
console.log("undefined in the storage so that we can use that variable in the code after some time" );